services:
  - type: web
    name: todo-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar -Dspring.profiles.active=prod target/todo-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: mysql://root:smZKEkvvkOyXbLDKYfzeDzqdBezWDRfh@mysql.railway.internal:3306/railway
        sync: false
      - key: root
        sync: false
      - key: smZKEkvvkOyXbLDKYfzeDzqdBezWDRfh
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
